frr version 10.4.1
frr defaults traditional
hostname r1
!

interface eth1
 ip address 10.0.0.1/30
 ip ospf cost 20
!

interface eth2
 ip address 10.0.0.9/30
 ip ospf cost 20
!

interface lo
 ip address 1.1.1.1/32
!

router ospf
 ospf router-id 1.1.1.1
 network 10.0.0.0/30 area 0
 network 10.0.0.4/30 area 0
 network 10.0.0.8/30 area 0
 network 1.1.1.1/32 area 0
!

line vty
!
